/**
 * Smart Contract Configuration
 *
 * This module provides type-safe access to deployed contract addresses
 * and network configuration for the Stellar blockchain.
 *
 * Environment variables are loaded from .env files generated by the
 * deployment script or manually configured for local development.
 */

interface ContractConfig {
  rwaDefiContractId: string | undefined;
  stellarNetwork: string;
  stellarRpcUrl: string;
  stellarHorizonUrl: string;
  stellarNetworkPassphrase: string;
}

interface NetworkConfig {
  name: string;
  rpcUrl: string;
  horizonUrl: string;
  passphrase: string;
}

/**
 * Predefined network configurations for different Stellar networks
 */
const NETWORKS: {
  testnet: NetworkConfig;
  mainnet: NetworkConfig;
  standalone: NetworkConfig;
  [key: string]: NetworkConfig | undefined;
} = {
  testnet: {
    name: 'testnet',
    rpcUrl: 'https://soroban-testnet.stellar.org',
    horizonUrl: 'https://horizon-testnet.stellar.org',
    passphrase: 'Test SDF Network ; September 2015',
  },
  mainnet: {
    name: 'mainnet',
    rpcUrl: 'https://rpc.mainnet.stellar.org',
    horizonUrl: 'https://horizon.stellar.org',
    passphrase: 'Public Global Stellar Network ; September 2015',
  },
  standalone: {
    name: 'standalone',
    rpcUrl: 'http://localhost:8000/soroban/rpc',
    horizonUrl: 'http://localhost:8000',
    passphrase: 'Standalone Network ; February 2017',
  },
};

/**
 * Get the current network configuration with fallback to defaults
 */
function getNetworkConfig(): NetworkConfig {
  const networkName = process.env.STELLAR_NETWORK || 'testnet';

  // Handle known networks directly to satisfy noUncheckedIndexedAccess
  if (networkName === 'testnet') return NETWORKS.testnet;
  if (networkName === 'mainnet') return NETWORKS.mainnet;
  if (networkName === 'standalone') return NETWORKS.standalone;

  const network = NETWORKS[networkName];

  if (network) {
    // Allow environment variable overrides
    return {
      name: networkName,
      rpcUrl: process.env.STELLAR_RPC_URL || network.rpcUrl,
      horizonUrl: process.env.STELLAR_HORIZON_URL || network.horizonUrl,
      passphrase: process.env.STELLAR_NETWORK_PASSPHRASE || network.passphrase,
    };
  }

  console.warn(`Unknown network: ${networkName}. Falling back to testnet.`);
  return NETWORKS.testnet;
}

/**
 * Load and validate contract configuration from environment variables
 */
function loadContractConfig(): ContractConfig {
  const network = getNetworkConfig();

  return {
    rwaDefiContractId: process.env.RWA_DEFI_CONTRACT_ID,
    stellarNetwork: network.name,
    stellarRpcUrl: network.rpcUrl,
    stellarHorizonUrl: network.horizonUrl,
    stellarNetworkPassphrase: network.passphrase,
  };
}

/**
 * Validate that required contract addresses are configured
 * Throws an error in production if contracts are not configured
 */
function validateContractConfig(config: ContractConfig): void {
  const errors: string[] = [];

  if (!config.rwaDefiContractId) {
    errors.push('RWA_DEFI_CONTRACT_ID is not configured');
  }

  if (errors.length > 0) {
    const errorMessage = [
      'Contract configuration is incomplete:',
      ...errors.map((e) => `  - ${e}`),
      '',
      'Please ensure contracts are deployed and environment variables are set.',
      'See docs/contracts/deployment.md for deployment instructions.',
    ].join('\n');

    // In development, log warning instead of throwing
    if (process.env.NODE_ENV === 'development') {
      console.warn(`[WARNING] ${errorMessage}`);
    } else {
      throw new Error(errorMessage);
    }
  }
}

/**
 * Contract configuration singleton
 */
const contractConfig = loadContractConfig();

// Validate on load in production
if (process.env.NODE_ENV !== 'test') {
  validateContractConfig(contractConfig);
}

/**
 * Export contract addresses and network configuration
 */
export const CONTRACTS = {
  /**
   * RWA DeFi Contract ID
   * Main contract handling real estate tokenization and DeFi operations
   */
  RWA_DEFI_CONTRACT_ID: contractConfig.rwaDefiContractId,
} as const;

/**
 * Export network configuration
 */
export const NETWORK_CONFIG = {
  NETWORK: contractConfig.stellarNetwork,
  RPC_URL: contractConfig.stellarRpcUrl,
  HORIZON_URL: contractConfig.stellarHorizonUrl,
  NETWORK_PASSPHRASE: contractConfig.stellarNetworkPassphrase,
} as const;

/**
 * Helper function to get contract ID with runtime validation
 */
export function getContractId(_contractName: 'rwa-defi'): string {
  const id = CONTRACTS.RWA_DEFI_CONTRACT_ID;

  if (!id) {
    throw new Error(
      `Contract ID for ${_contractName} is not configured. ` +
        'Ensure RWA_DEFI_CONTRACT_ID environment variable is set.',
    );
  }

  return id;
}

/**
 * Helper to check if contracts are configured
 */
export function isContractConfigured(_contractName: 'rwa-defi'): boolean {
  return !!CONTRACTS.RWA_DEFI_CONTRACT_ID;
}

/**
 * Export all configuration as a single object for convenience
 */
export const config = {
  contracts: CONTRACTS,
  network: NETWORK_CONFIG,
  getContractId,
  isContractConfigured,
} as const;

export default config;
